### ISSUE TITLE
MD5

### ISSUE THREAD

**Issue by Vizis** [games647/FlexibleLogin#100]
can you add option to use md5 password hash?
Because i want to make shop on my web page and check if password which user insert in login formula match to assword in DB of plugin.. password test in game has diffrent result than php funcions:
echo password_hash('test', PASSWORD_DEFAULT)."\n";
echo password_hash('test', PASSWORD_BCRYPT)."\n";

**Comment by games647** [comment]
No I will never add MD5. It's **way too insecure**. As you already noticed PHP uses BCrypt by default. The BCrypt functions only differ in the version prefix which you can just replace ($2a -> $2y). In fact FlexibleLogin uses now the PHP variant since a couple of versions for new passwords.

**Comment by Vizis** [comment]
But every time i refresh my page my password looks diffrent in php:S

**Comment by games647** [comment]
This is intended. BCrypt automatically creates a random salt to make the password hash more unique. This makes it a lot harder to build a password -> password hash database in order to crack passwords.

You should use the [`password_verify`](https://secure.php.net/manual/en/function.password-verify.php) to compare the passwords on login. This function extracts the salt (the first x characters included in the hash) and cost factor. Then hashes the input password using the extracted configuration and compares the two passwords.

**Comment by Vizis** [comment]
Than you My Master :)! I allways used to use double md5 instead of BCrypt.. now i more educated.
For others:
if (password_verify('test', $db_password)) {
    echo 'Password is valid!';
} else {
    echo 'Invalid password.';
}
