### ISSUE TITLE
Bungee prevent command support

### ISSUE THREAD

**Issue by Flashback083** [games647/FlexibleLogin#108]
Hello ! I want to make a Lobby SpongeVanilla server with FlexibleLogin.
I have a bungee (waterfall) server. Also, when a player join the server, he is able to do all bungee command before be connect with /login <password> do you know how we can fix that ?
Thanks !

**Comment by games647** [comment]
This requires a BungeeCord plugin and so isn't possible from Sponge plugins alone.

**Comment by Flashback083** [comment]
Yeah, like BungeeAuthBridge, okay thanks !

**Comment by user38898892** [comment]
May i know if this function still works in version 0.17.4 and how can i do to make it works?

**Comment by games647** [comment]
It's still supported. If you install AuthMeBridge, it will send a message to that plugin to unlock you like the normal AuthMe does.

**Comment by user38898892** [comment]
> Installation
1.Download AuthMeBridge package
2.Place BungeeAuthMeBridge.jar into your BungeeCord's plugin folder
3.Place AuthMeBridge.jar (or xAuthBridge.jar if you're using xAuth) into your servers' plugin folders
4.Install and configure IPWhitelist on ALL your servers
5.Restart everything
6.Configure the bungee-side plugin (don't forget to config serversList)
7.Enjoy!

The above is the installation steps of AuthMeBridge.
But I get stuck on step 3 since i think spongeforge couldn't load AuthMeBridge.jar.
Thank you for the help.
