### ISSUE TITLE
VirusTotal Detection

### ISSUE THREAD

**Issue by jerbear2008** [games647/FlexibleLogin#184]
I am pretty sure this is safe, but [VirusTotal](https://www.virustotal.com/gui/file/9990a11e50d82c4aee5c46d48ea5e9fe4fa0849d03df48c9c17d49b5767af01c/detection) is showing 7/54 detections as Java.Trojan.GenericGB.29215. Is there a reason this is a detection?

**Comment by TuxCoding** [comment]
False positive. It could be due to the inclusion of BCrypt for hashing the passwords and including an email library. Both could be strong indicators. However everyone could check the code and compile it on their own. There is no Trojan it. I also took a short peak at the dependencies and it seems safe there too.

**Comment by jerbear2008** [comment]
Yeah, that's what I thought. Thanks for confirming though.
