### ISSUE TITLE
Lang file for sponge plugin

### ISSUE THREAD

**Issue by iTeeLion** [games647/FlexibleLogin#24]
Hi! Add the lang file/class please. I wanna translate your plugin ^_^

**Comment by games647** [comment]
It#s already there. The message files in your config folder.

**Comment by SourcePowered** [comment]
@games647 Oh sir! I think we can do this:
1. Create a folder named "Messages" or "messages" (Oh case size is not a problem...... :P)...
2. Create some lang files like:
message_en
message_zhcn
message_ru
message_(country code)
We don't need a file suffix (like *.lang), because the meaning of "message" is very clear.
3. In config file, users can change what language file they need to use.
4. Done!!!
