### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by TekuSP** [games647/FlexibleLogin#65]
I want ability to set times between "Use /register to register." and login.

**Comment by games647** [comment]
You mean when the message prints out?

**Comment by TekuSP** [comment]
Yup. I want message every 20 seconds for example.
```
Use /register to register.
20 seconds break.
Use /register to register
```

**Comment by TekuSP** [comment]
Thank you!~

**Comment by TekuSP** [comment]
Can I please ask for compiled version (Release)? I have problems with compiling it on my own (my fault probably, I do not like maven) @games647

**Comment by games647** [comment]
Uploaded. 

If you still want to know how to compile it:
1. Download Maven from Apache
2. Unpack it and put it somewhere
(3. Now put the MAVEN_FOLDER/bin into your PATH variable in order to access maven easily from everywhere)
4. Jump to the FlexibleLogin using a terminal. 
5. If you did step 3 you could just run `mvn clean package`
    Otherwise you have to specify the fully qualified path `PATH_TO_MAVEN/bin/mvn clean package`
6. Then you could use the compiled version from the target/ folder

FYI: `clean` removes previously compiled files. Sometimes this necessary if you use constants across multiple files and you want to update all of them

`package` builds the project and packages it into a jar file

BTW: You don't need to tag me if I already replied to the ticket and I am the only one who replied.
